export const copy = {
  skip: 'Skip to content',
  homeLabel: 'Veyit home',
  primaryNavigation: 'Primary navigation',
  nav: ['Home', 'Verified sellers', 'How it works', 'Pricing', 'About'],
  openStore: 'Open your store',
  menu: 'Open navigation',
  theme: 'Toggle colour theme',
  eyebrow: 'Built for Telegram merchants',
  heroTitle: 'Your Telegram bot. Now it runs the store.',
  heroBody: 'Sell digital products, verify exchange payments, and deliver every order in seconds. No code. No commission. Your money stays yours.',
  primaryCta: 'Start for $4.99',
  secondaryCta: 'Watch the flow',
  activation: 'One week trial by promo code · Activation is reviewed manually',
  order: 'Telegram order',
  matched: 'Payment matched',
  matchMeta: 'UID · amount · currency',
  delivered: 'Delivered in seconds',
  orbitLabels: ['Telegram', 'Binance', 'Tether', 'Steam', 'PlayStation', 'Google Play'],
  promises: ['No code', 'Zero commission', 'Instant delivery'],
  flowKicker: 'One clean flow',
  flowTitle: 'From “buy” to delivered—before the chat gets cold.',
  flowBody: 'One continuous system handles the order, checks the transfer, and releases stock. The 3D scene follows the exact same journey.',
  beats: [
    { number: '01', title: 'Order', body: 'Your customer chooses one digital product inside Telegram. A clean, time-limited order is created.' },
    { number: '02', title: 'Verify', body: 'Veyit matches UID, amount, currency, time window, and an unused transfer ID against your own exchange account.' },
    { number: '03', title: 'Deliver', body: 'The stock item is decrypted, sent in chat, and locked from being sold twice.' },
  ],
  sceneLabels: ['Order received', 'Matching transfer', 'Stock delivered'],
  trustKicker: 'Built for suspicious people. On purpose.',
  trustTitle: 'The safest money is money we never touch.',
  trustBody: 'Buyers pay straight into your own Binance or Bybit account. Veyit does not hold, move, or settle funds—and takes zero commission on sales.',
  trustCards: [
    { index: '01', title: 'Your account', body: 'Retail and wholesale payments settle directly between the people trading.' },
    { index: '02', title: 'Your margin', body: 'A simple subscription replaces percentage fees. What you earn stays yours.' },
    { index: '03', title: 'Your stock', body: 'Encrypted inventory is released once and only once after a valid match.' },
  ],
  catalogueKicker: 'One bot. Many shelves.',
  catalogueTitle: 'Built for the products Telegram already buys.',
  catalogue: [
    { title: 'Game top-ups', tag: 'Instant credit', mark: 'XP' },
    { title: 'Gift cards', tag: 'Codes & vouchers', mark: 'GV' },
    { title: 'Licence keys', tag: 'Software access', mark: 'KEY' },
    { title: 'Subscriptions', tag: 'Digital access', mark: 'PRO' },
  ],
  networkKicker: 'The verified seller network',
  networkTitle: 'Find supply. Build status. Become the store others trust.',
  networkBody: 'Veyit is also a public network for merchants. Browse accredited suppliers, understand what they offer, and work toward a badge merchants actively look for.',
  profileLabel: 'Your storefront',
  profileBody: 'A profile built from activity Veyit can actually verify—not paid placement or invented reviews.',
  badgeDate: 'Verified by Veyit',
  badgeGranted: 'Granted after qualification + human review',
  networkPoints: ['Public supplier discovery', 'Featured digital services', 'Activity shown as honest ranges', 'No paid verification badge'],
  badgeCta: 'How the badge works',
  pricingKicker: 'Start small. Keep the upside.',
  pricingTitle: 'A storefront for less than one manual mistake.',
  starter: 'Starter',
  perMonth: '/ month',
  starterBody: 'For merchants ready to automate the daily grind.',
  limits: ['1 Telegram store', 'Up to 100 products', 'Up to 1,000 monthly orders', 'Owner + 1 staff seat', 'Zero sales commission'],
  priceCta: 'Start the manual review',
  expiry: '3-day grace period after expiry. Then limited mode—your data is never deleted.',
  business: 'Business',
  businessPrice: 'Price pending owner approval',
  businessBody: 'More stores, products, staff, and full network access for scaling merchants.',
  businessCta: 'Talk to Veyit',
  closeKicker: 'Ready when your next order is.',
  closeTitle: 'Stop copying UIDs at 2am.',
  closeBody: 'Connect a bot, add products and stock, then let the store handle the repeatable work.',
  footerLine: 'Telegram commerce, automated.',
  legalNote: 'Veyit never holds funds and is not a party to merchant-to-merchant trades.',
  sectionAria: 'Animated order, verification, and delivery flow',
};

export type SiteCopy = typeof copy;
