export type Locale = 'en' | 'hi';

export const copy = {
  en: {
    locale: 'en' as Locale,
    language: 'हिंदी',
    languageLabel: 'Switch to Hindi',
    nav: ['Home', 'Verified sellers', 'How it works', 'Pricing', 'About'],
    openStore: 'Open your store',
    menu: 'Open navigation',
    theme: 'Toggle colour theme',
    eyebrow: 'Built for Telegram merchants',
    heroTitle: 'Your Telegram bot. Now it runs the store.',
    heroBody: 'Sell digital products, verify exchange payments, and deliver every order in seconds. No code. No commission. Your money stays yours.',
    primaryCta: 'Start for $4.99',
    secondaryCta: 'Watch the flow',
    activation: 'One week trial by promo code · Activation is reviewed manually',
    order: 'Telegram order',
    matched: 'Payment matched',
    matchMeta: 'UID · amount · currency',
    delivered: 'Delivered in seconds',
    orbitLabels: ['Telegram', 'USDT', 'Games', 'Gift cards', 'Keys', 'Bots'],
    promises: ['No code', 'Zero commission', 'Instant delivery'],
    flowKicker: 'One clean flow',
    flowTitle: 'From “buy” to delivered—before the chat gets cold.',
    flowBody: 'One continuous system handles the order, checks the transfer, and releases stock. The 3D scene follows the exact same journey.',
    beats: [
      { number: '01', title: 'Order', body: 'Your customer chooses one digital product inside Telegram. A clean, time-limited order is created.' },
      { number: '02', title: 'Verify', body: 'Veyit matches UID, amount, currency, time window, and an unused transfer ID against your own exchange account.' },
      { number: '03', title: 'Deliver', body: 'The stock item is decrypted, sent in chat, and locked from being sold twice.' },
    ],
    sceneLabels: ['Order received', 'Matching transfer', 'Stock delivered'],
    trustKicker: 'Built for suspicious people. On purpose.',
    trustTitle: 'The safest money is money we never touch.',
    trustBody: 'Buyers pay straight into your own Binance or Bybit account. Veyit does not hold, move, or settle funds—and takes zero commission on sales.',
    trustCards: [
      { index: '01', title: 'Your account', body: 'Retail and wholesale payments settle directly between the people trading.' },
      { index: '02', title: 'Your margin', body: 'A simple subscription replaces percentage fees. What you earn stays yours.' },
      { index: '03', title: 'Your stock', body: 'Encrypted inventory is released once and only once after a valid match.' },
    ],
    catalogueKicker: 'One bot. Many shelves.',
    catalogueTitle: 'Built for the products Telegram already buys.',
    catalogue: [
      { title: 'Game top-ups', tag: 'Instant credit', mark: 'XP' },
      { title: 'Gift cards', tag: 'Codes & vouchers', mark: 'GV' },
      { title: 'Licence keys', tag: 'Software access', mark: 'KEY' },
      { title: 'Subscriptions', tag: 'Digital access', mark: 'PRO' },
    ],
    networkKicker: 'The verified seller network',
    networkTitle: 'Find supply. Build status. Become the store others trust.',
    networkBody: 'Veyit is also a public network for merchants. Browse accredited suppliers, understand what they offer, and work toward a badge merchants actively look for.',
    profileLabel: 'Your storefront',
    profileBody: 'A profile built from activity Veyit can actually verify—not paid placement or invented reviews.',
    badgeDate: 'Verified by Veyit',
    badgeGranted: 'Granted after qualification + human review',
    networkPoints: ['Public supplier discovery', 'Featured digital services', 'Activity shown as honest ranges', 'No paid verification badge'],
    badgeCta: 'How the badge works',
    pricingKicker: 'Start small. Keep the upside.',
    pricingTitle: 'A storefront for less than one manual mistake.',
    starter: 'Starter',
    perMonth: '/ month',
    starterBody: 'For merchants ready to automate the daily grind.',
    limits: ['1 Telegram store', 'Up to 100 products', 'Up to 1,000 monthly orders', 'Owner + 1 staff seat', 'Zero sales commission'],
    priceCta: 'Start the manual review',
    expiry: '3-day grace period after expiry. Then limited mode—your data is never deleted.',
    business: 'Business',
    businessPrice: 'Price pending owner approval',
    businessBody: 'More stores, products, staff, and full network access for scaling merchants.',
    businessCta: 'Talk to Veyit',
    closeKicker: 'Ready when your next order is.',
    closeTitle: 'Stop copying UIDs at 2am.',
    closeBody: 'Connect a bot, add products and stock, then let the store handle the repeatable work.',
    footerLine: 'Telegram commerce, automated.',
    legalNote: 'Veyit never holds funds and is not a party to merchant-to-merchant trades.',
    sectionAria: 'Animated order, verification, and delivery flow',
  },
  hi: {
    locale: 'hi' as Locale,
    language: 'English',
    languageLabel: 'Switch to English',
    nav: ['होम', 'सत्यापित विक्रेता', 'कैसे काम करता है', 'कीमत', 'हमारे बारे में'],
    openStore: 'अपना स्टोर खोलें',
    menu: 'नेविगेशन खोलें',
    theme: 'रंग थीम बदलें',
    eyebrow: 'Telegram व्यापारियों के लिए बनाया गया',
    heroTitle: 'आपका Telegram bot। अब स्टोर खुद चलता है।',
    heroBody: 'डिजिटल प्रोडक्ट बेचें, एक्सचेंज पेमेंट सत्यापित करें और हर ऑर्डर सेकंडों में डिलीवर करें। बिना कोड। बिना कमीशन। आपका पैसा आपके पास।',
    primaryCta: '$4.99 से शुरू करें',
    secondaryCta: 'पूरा फ्लो देखें',
    activation: 'प्रोमो कोड से एक सप्ताह का ट्रायल · एक्टिवेशन की मैन्युअल समीक्षा होती है',
    order: 'Telegram ऑर्डर',
    matched: 'पेमेंट मैच हुआ',
    matchMeta: 'UID · राशि · करेंसी',
    delivered: 'सेकंडों में डिलीवर',
    orbitLabels: ['Telegram', 'USDT', 'गेम्स', 'गिफ्ट कार्ड', 'Keys', 'Bots'],
    promises: ['बिना कोड', 'शून्य कमीशन', 'तुरंत डिलीवरी'],
    flowKicker: 'एक साफ़ फ्लो',
    flowTitle: '“Buy” से डिलीवरी तक—चैट ठंडी होने से पहले।',
    flowBody: 'एक लगातार चलने वाला सिस्टम ऑर्डर संभालता है, ट्रांसफ़र जाँचता है और स्टॉक रिलीज़ करता है। 3D दृश्य भी यही सफ़र दिखाता है।',
    beats: [
      { number: '01', title: 'ऑर्डर', body: 'ग्राहक Telegram में एक डिजिटल प्रोडक्ट चुनता है। एक साफ़, समय-सीमित ऑर्डर बनता है।' },
      { number: '02', title: 'सत्यापन', body: 'Veyit आपके अपने एक्सचेंज अकाउंट पर UID, राशि, करेंसी, समय और अप्रयुक्त ट्रांसफ़र ID मिलाता है।' },
      { number: '03', title: 'डिलीवरी', body: 'स्टॉक डिक्रिप्ट होकर चैट में भेजा जाता है और दोबारा बिकने से लॉक हो जाता है।' },
    ],
    sceneLabels: ['ऑर्डर मिला', 'ट्रांसफ़र मिल रहा है', 'स्टॉक डिलीवर हुआ'],
    trustKicker: 'संदेह करने वाले लोगों के लिए। जानबूझकर।',
    trustTitle: 'सबसे सुरक्षित पैसा वह है जिसे हम कभी छूते ही नहीं।',
    trustBody: 'खरीदार सीधे आपके Binance या Bybit अकाउंट में भुगतान करते हैं। Veyit फंड नहीं रखता, चलाता या सेटल करता—और बिक्री पर शून्य कमीशन लेता है।',
    trustCards: [
      { index: '01', title: 'आपका अकाउंट', body: 'रिटेल और होलसेल भुगतान सीधे व्यापार करने वालों के बीच सेटल होते हैं।' },
      { index: '02', title: 'आपका मार्जिन', body: 'प्रतिशत फीस की जगह सरल सब्सक्रिप्शन। आपकी कमाई आपकी रहती है।' },
      { index: '03', title: 'आपका स्टॉक', body: 'वैध मैच के बाद एन्क्रिप्टेड इन्वेंटरी सिर्फ़ एक बार रिलीज़ होती है।' },
    ],
    catalogueKicker: 'एक bot। कई shelves।',
    catalogueTitle: 'उन प्रोडक्ट्स के लिए जो Telegram पर पहले से बिकते हैं।',
    catalogue: [
      { title: 'गेम टॉप-अप', tag: 'तुरंत क्रेडिट', mark: 'XP' },
      { title: 'गिफ्ट कार्ड', tag: 'कोड और वाउचर', mark: 'GV' },
      { title: 'लाइसेंस keys', tag: 'सॉफ्टवेयर एक्सेस', mark: 'KEY' },
      { title: 'सब्सक्रिप्शन', tag: 'डिजिटल एक्सेस', mark: 'PRO' },
    ],
    networkKicker: 'सत्यापित विक्रेता नेटवर्क',
    networkTitle: 'सप्लाई खोजें। पहचान बनाएँ। वह स्टोर बनें जिस पर लोग भरोसा करें।',
    networkBody: 'Veyit व्यापारियों का सार्वजनिक नेटवर्क भी है। मान्य सप्लायर खोजें, उनकी सेवाएँ समझें और उस badge के लिए आगे बढ़ें जिसे व्यापारी सच में देखते हैं।',
    profileLabel: 'आपका storefront',
    profileBody: 'ऐसी गतिविधि से बनी प्रोफ़ाइल जिसे Veyit सच में जाँच सकता है—कोई paid placement या नकली review नहीं।',
    badgeDate: 'Veyit द्वारा सत्यापित',
    badgeGranted: 'योग्यता + मानवीय समीक्षा के बाद दिया गया',
    networkPoints: ['सार्वजनिक सप्लायर खोज', 'Featured डिजिटल सेवाएँ', 'ईमानदार ranges में गतिविधि', 'कोई paid verification badge नहीं'],
    badgeCta: 'Badge कैसे मिलता है',
    pricingKicker: 'छोटा शुरू करें। फ़ायदा अपना रखें।',
    pricingTitle: 'एक manual गलती से भी कम में पूरा storefront।',
    starter: 'Starter',
    perMonth: '/ महीना',
    starterBody: 'रोज़ के दोहराव वाले काम को automate करने वाले व्यापारियों के लिए।',
    limits: ['1 Telegram स्टोर', '100 तक प्रोडक्ट', '1,000 तक मासिक ऑर्डर', 'Owner + 1 staff seat', 'बिक्री पर शून्य कमीशन'],
    priceCta: 'Manual review शुरू करें',
    expiry: 'Expiry के बाद 3 दिन grace period। फिर limited mode—आपका data कभी delete नहीं होता।',
    business: 'Business',
    businessPrice: 'कीमत owner approval के बाद',
    businessBody: 'बढ़ते व्यापारियों के लिए अधिक स्टोर, प्रोडक्ट, staff और पूरा network access।',
    businessCta: 'Veyit से बात करें',
    closeKicker: 'आपके अगले ऑर्डर के लिए तैयार।',
    closeTitle: 'रात 2 बजे UID कॉपी करना बंद करें।',
    closeBody: 'Bot जोड़ें, प्रोडक्ट और स्टॉक डालें, फिर दोहराव वाला काम storefront को करने दें।',
    footerLine: 'Telegram commerce, automated.',
    legalNote: 'Veyit फंड नहीं रखता और व्यापारी-से-व्यापारी ट्रेड का पक्ष नहीं है।',
    sectionAria: 'ऑर्डर, सत्यापन और डिलीवरी का एनिमेटेड फ्लो',
  },
};

export type SiteCopy = typeof copy.en;
