export const copy = {
  skip: 'Skip to content',
  homeLabel: 'Veyit home',
  primaryNavigation: 'Primary navigation',
  nav: ['Home', 'Beyond', 'How it works', 'Pricing', 'About'],
  openStore: 'Open your store',
  menu: 'Open navigation',
  theme: 'Toggle colour theme',
  eyebrow: 'Built for Telegram merchants',
  heroTitle: 'Your Telegram bot. Now it runs the store.',
  heroBody: 'Sell digital products, verify exchange payments, and deliver every order in seconds. No code. No commission. Your money stays yours.',
  primaryCta: 'Start for $4.99',
  secondaryCta: 'Watch the flow',
  activation: 'One week trial by promo code · Activation is reviewed manually',
  order: 'Telegram order',
  matched: 'Payment matched',
  matchMeta: 'UID · amount · currency',
  delivered: 'Delivered in seconds',
  orbitLabels: ['Telegram', 'Binance', 'Tether', 'Steam', 'PlayStation', 'Google Play'],
  promises: ['No code', 'Zero commission', 'Instant delivery'],
  flowKicker: 'One clean flow',
  flowTitle: 'From “buy” to delivered—before the chat gets cold.',
  flowBody: 'One continuous system handles the order, checks the transfer, and releases stock. The live product view follows the exact same journey.',
  beats: [
    { number: '01', title: 'Order', body: 'Your customer chooses one digital product inside Telegram. A clean, time-limited order is created.' },
    { number: '02', title: 'Verify', body: 'Veyit matches UID, amount, currency, time window, and an unused transfer ID against your own exchange account.' },
    { number: '03', title: 'Deliver', body: 'The stock item is decrypted, sent in chat, and locked from being sold twice.' },
  ],
  sceneLabels: ['Order received', 'Matching transfer', 'Stock delivered'],
  flowVisual: {
    progressLabel: 'Live order progress',
    states: [
      {
        stage: 'ORDER 01',
        title: 'New Telegram order',
        caption: 'One digital product · expires in 15:00',
        primary: 'Game credit',
        secondary: 'Order created',
        fields: [
          { label: 'Item', value: '1 product' },
          { label: 'Status', value: 'Awaiting transfer' },
        ],
      },
      {
        stage: 'VERIFY 02',
        title: 'Payment matched',
        caption: 'Checked against your exchange account',
        primary: '5 checks passed',
        secondary: 'Unused transfer UID',
        fields: [
          { label: 'UID', value: 'Matched' },
          { label: 'Amount', value: 'Matched' },
          { label: 'Currency', value: 'Matched' },
          { label: 'Time window', value: 'Valid' },
        ],
      },
      {
        stage: 'DELIVER 03',
        title: 'Stock released',
        caption: 'Decrypted once and sent in Telegram',
        primary: 'Delivered',
        secondary: 'Protected from double-selling',
        fields: [
          { label: 'Stock', value: 'Sent securely' },
          { label: 'Order', value: 'Complete' },
        ],
      },
    ],
  },
  launch: {
    sectionLabel: 'Cinematic launch transition',
    loadingLabel: 'Preparing launch sequence',
    eyebrow: 'Built to go further.',
    title: 'Commerce without borders.',
    body: 'Veyit gives digital merchants the infrastructure to sell, automate, and scale without getting in the way of the transaction.',
  },
  pricingKicker: 'Start small. Keep the upside.',
  pricingTitle: 'A storefront for less than one manual mistake.',
  starter: 'Starter',
  perMonth: '/ month',
  starterBody: 'For merchants ready to automate the daily grind.',
  limits: ['1 Telegram store', 'Up to 100 products', 'Up to 1,000 monthly orders', 'Owner + 1 staff seat', 'Zero sales commission'],
  priceCta: 'Start the manual review',
  expiry: '3-day grace period after expiry. Then limited mode—your data is never deleted.',
  business: 'Business',
  businessPrice: 'Price pending owner approval',
  businessBody: 'More stores, products, staff, and full network access for scaling merchants.',
  businessCta: 'Talk to Veyit',
  closeKicker: 'Ready when your next order is.',
  closeTitle: 'Stop copying UIDs at 2am.',
  closeBody: 'Connect a bot, add products and stock, then let the store handle the repeatable work.',
  footerLine: 'Telegram commerce, automated.',
  legalNote: 'Veyit never holds funds and is not a party to merchant-to-merchant trades.',
  sectionAria: 'Animated order, verification, and delivery flow',
};

export type SiteCopy = typeof copy;
